services:
  outreach_backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    volumes:
      - ../outreach_agent:/app/outreach_agent
      - ../data:/app/data
      - ../env.json:/app/env.json
    working_dir: /app
    restart: unless-stopped
volumes:
  db_data: